#!/bin/bash
#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -J lingam-serial
#SBATCH -t 00:30:00

#run the application:
srun -n 1 -c 1 --cpu_bind=cores ./LiNGAM -i ../synthetic/X_S_500_1024_0.csv -o X_S_500_1024_0.out

